graph TD
    A[Inicio] --> B[/Cargar Audio Pre A y Post B/]
    B --> C[Aplicar Reducción de Ruido Noisereduce]
    C --> D[Aplicar FFT]
    D --> E["Calcular Magnitud Espectral |X(k)|"]
    E --> F{¿Es comparativo?}
    F -- Sí --> G[Generar Gráfica A vs B]
    F -- No --> H[Generar Gráfica Individual]
    G --> I[/"Exportar Datos DB-.csv y DB-.txt"/]
    H --> I
    I --> J[Fin]
